apiVersion: v1
kind: Pod
metadata:
  name: mysql-nginx
spec:
  containers:
    - name: mysql
      image: mysql
      ports:
        - containerPort: 8080
    - name : nginx
      image : nginx
      ports :
         - containerPort: 80    