apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label
  labels:
    team: makerindo
    version: 1.2.3
    environment: production
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80